### Creating DB ###

DROP DATABASE IF EXISTS `SIAADB`;
CREATE DATABASE `SIAADB` CHARSET=utf8 COLLATE=UTF8_SPANISH_CI;
USE `SIAADB`;

### Creating Tables ###

/* ACTIVIDAD, USUARIO/AUTOR, ADMINISTRACION */

CREATE TABLE `ACTIVIDAD`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`FECHA_CRE` DATE,
	`ACTIVIDAD` VARCHAR(255),
	`DESCRIPCION` VARCHAR(255),
	`FECHA_IN` DATE,
	`FECHA_FI` DATE,
	`ID_ESTATUS` INT,
	`ID_USER` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `USUARIO`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	`APELLIDO` VARCHAR(255),
	`USUARIO` VARCHAR(255),
	`CLAVE` VARCHAR(255),
	`ID_ADMIN` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `ADMINISTRACION`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`TIPO` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE `ESTATUS`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`TIPO` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

ALTER TABLE `ACTIVIDAD`
	ADD FOREIGN KEY (`ID_USER`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ACTIVIDAD`
	ADD FOREIGN KEY (`ID_ESTATUS`) REFERENCES `ESTATUS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `USUARIO`
	ADD FOREIGN KEY (`ID_ADMIN`) REFERENCES `ADMINISTRACION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO `ADMINISTRACION` (`TIPO`) VALUES
	('SUPERUSUARIO');

INSERT INTO `ADMINISTRACION` (`TIPO`) VALUES
	('USUARIO');

INSERT INTO `ESTATUS` (`TIPO`) VALUES
	('VISIBLE');

INSERT INTO `ESTATUS` (`TIPO`) VALUES
	('INVISIBLE');

INSERT INTO `USUARIO` (`USUARIO`,`NOMBRE`,`APELLIDO`,`CLAVE`,`ID_ADMIN`) VALUES
	('admin','admin','admin','Granda3941$$',1);

INSERT INTO `USUARIO` (`USUARIO`,`NOMBRE`,`APELLIDO`,`CLAVE`,`ID_ADMIN`) VALUES
	('Juan','Palencia','JPADM','Palencia..22',1);
